[snapshot]
date = 2025-12-01

[scope]
lad_names = [
    "Exeter",
    "Plymouth",
    "Newcastle upon Tyne",
    "Bournemouth, Christchurch and Poole",
    "Bristol, City of",
    "Sheffield",
]
# lad_names = ["""Bristol, City of", "Newcastle upon Tyne", "Exeter", "Plymouth"]
